// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} deviceType
 * @param {number} deviceID
 * @returns {$CancellablePromise<boolean>}
 */
export function ChangeDevice(deviceType, deviceID) {
    return $Call.ByID(3515118737, deviceType, deviceID);
}

/**
 * @returns {$CancellablePromise<$models.MidiDevices>}
 */
export function GetMidiDevices() {
    return $Call.ByID(1374315843).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardPlay(key) {
    return $Call.ByID(3061755184, key);
}

/**
 * @param {number} key
 * @returns {$CancellablePromise<void>}
 */
export function KeyboardStop(key) {
    return $Call.ByID(1684431926, key);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStart() {
    return $Call.ByID(3822394978);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MidiListenerStop() {
    return $Call.ByID(1572563810);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenUrl(url) {
    return $Call.ByID(205994420, url);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3653247816);
}

/**
 * @param {$models.Config} config
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function ReceiveConfig(config) {
    return $Call.ByID(414621010, config);
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function ResetConfig() {
    return $Call.ByID(2912551192).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function SendConfig() {
    return $Call.ByID(1326898251).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MidiDevices.createFrom;
const $$createType1 = $models.Config.createFrom;
